spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://localhost:3306/infuse?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: 'true'
    locations: classpath:db/migration
    outOfOrder: 'false'
    url: jdbc:mysql://localhost:3306/infuse?createDatabaseIfNotExist=true&serverTimezone=UTC
    user: root
    password: root
    baselineOnMigrate: true
