spring:
  application:
    name: orders
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/infuse?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: 'true'
    locations: classpath:db/migration,classpath:db/seed
    outOfOrder: 'true'
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/infuse?createDatabaseIfNotExist=true&serverTimezone=UTC}
    user: ${DB_USER:root}
    password: ${DB_PASS:root}
    baselineOnMigrate: false
